# Generated by Django 5.1.6 on 2025-02-12 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_adresse_customuser_confirmation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='adress',
        ),
    ]
