# Generated by Django 5.1.6 on 2025-02-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='domaine_expeertise',
            new_name='domaine_expertise',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='nom_enrtreprise',
            new_name='nom_agence',
        ),
        migrations.AddField(
            model_name='profile',
            name='nom_entreprise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
