# Generated by Django 5.1.6 on 2025-03-03 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_domaine_expeertise_profile_domaine_expertise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDeBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('appartements', models.CharField(choices=[('atelier', 'Atelier'), ('boutique', 'Boutique'), ('maison', 'Maison'), ('parking', 'Parking')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifiant', models.CharField(choices=[('description', 'Description'), ('superficie', 'Superficie (m²)'), ('nombre_de_piece', 'Nombre de pièce'), ('unite', 'Unité')], max_length=50)),
                ('photo', models.ImageField(upload_to='biens_photos/')),
                ('description', models.TextField()),
                ('pays', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('prefecture', models.CharField(max_length=100)),
                ('sous_prefecture', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('type_de_location', models.CharField(choices=[('meublé', 'Meublé'), ('vide', 'Vide')], max_length=50)),
                ('frequence_de_paiement', models.CharField(choices=[('mensuel', 'Mensuel'), ('bimestriel', 'Bimestriel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel'), ('forfetaire', 'Forfetaire')], max_length=50)),
                ('type_de_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.typedebien')),
            ],
        ),
    ]
