# Generated by Django 5.1.6 on 2025-03-19 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_typedebien_bien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='frequence_de_paiement',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='identifiant',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='prefecture',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='quartier',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='region',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='sous_prefecture',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='type_de_location',
        ),
        migrations.AddField(
            model_name='bien',
            name='annee_construction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='charges_mensuelles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='etat_bien',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='materiaux_construction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='mode_paiement_accepte',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='nombre_pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='periodicite_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='prix_location',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='prix_vente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='reference',
            field=models.CharField(default=1, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='statut',
            field=models.CharField(default='disponible', max_length=255),
        ),
        migrations.AddField(
            model_name='bien',
            name='surface_habitable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='surface_totale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bien',
            name='taxe_fonciere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='titre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bien',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='type_de_bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.typedebien'),
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(max_length=50)),
                ('type_contrat', models.CharField(choices=[('location', 'Location'), ('vente', 'Vente'), ('bail', 'Bail'), ('gestion', 'Gestion')], max_length=20)),
                ('date_signature', models.DateField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('duree_contrat', models.CharField(max_length=50)),
                ('statut_contrat', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('desiste', 'Désisté'), ('expire', 'Expiré')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(max_length=100)),
                ('periodicite_paiement', models.CharField(max_length=50)),
                ('caution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_urgence', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('penalites_retard', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('clause_resiliation_anticipee', models.TextField(blank=True, null=True)),
                ('clause_revision_prix', models.TextField(blank=True, null=True)),
                ('clause_entretien', models.TextField(blank=True, null=True)),
                ('clause_sous_location', models.CharField(choices=[('autorise', 'Autorisé'), ('interdit', 'Interdit')], default='interdit', max_length=20)),
                ('assurance', models.TextField(blank=True, null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='user.bien')),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_complete', models.TextField()),
                ('quartier', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('prefecture', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localisation', to='user.bien')),
            ],
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.TextField()),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locataires', to='user.bien')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locataire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField()),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='user.locataire')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bien',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biens', to='user.proprietaire'),
        ),
    ]
